**### Loading Data from Table Sample_Superstore Excel File**

Upload the 'Sample_Superstore.xlsx` file to the Colab environment, and load "Orders" sheet

In [32]:
import pandas as pd
#Load the 'Orders' sheet into the variable
orders = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Assignments/Sample_Superstore.xls', sheet_name='Orders')
print(orders.shape)
orders.info()
orders.describe()

(9994, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

### Merging the three Superstore sheets into a single DataFrame

**#### Loading the 'Orders' Sheet (first 5000 rows)**
PART B

In [33]:
# Load the 'Orders' sheet, taking only the first 5000 rows
orders = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Assignments/Sample_Superstore.xls', sheet_name='Orders', nrows=5000)

# Display the first 5 rows of the 'Orders' DataFrame
display(orders.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

#### Loading the 'People' Sheet

In [34]:
# Load the 'People' sheet
people = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Assignments/Sample_Superstore.xls', sheet_name='People')

# Display the first 5 rows of the 'People' DataFrame
display(people.head())

              Person   Region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

#### Loading the 'Returns' Sheet

In [35]:
# Load the 'Returns' sheet
returns = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Assignments/Sample_Superstore.xls', sheet_name='Returns')

# Display the first 5 rows of the 'Returns' DataFrame
display(returns.head())

  Returned        Order ID
0      Yes  CA-2017-153822
1      Yes  CA-2017-129707
2      Yes  CA-2014-152345
3      Yes  CA-2015-156440
4      Yes  US-2017-155999

In [36]:
# Merge 'orders' with 'returns' using a left join on 'Order ID'
# We use a left join here to ensure that all orders are retained, and return information is added only for the orders that have been returned.
# For orders that were not returned, the 'Returned' column will contain NaN, which can be handled later if needed.
final_dataset = orders.merge(returns, on='Order ID', how='left')
# Storing merged final dataset to excel file
final_dataset.to_excel("/content/drive/MyDrive/Colab Notebooks/Assignments/Merged_Superstore.xlsx", index=False)

# Fill NaN values in 'Returned' column with 'No' (assuming orders not in 'returns' were not returned)
final_dataset['Returned'] = final_dataset['Returned'].fillna('No')

# Merge the result with 'people' using a left join on 'Region'
# A left join is appropriate here to keep all orders and their associated return status, and then append the regional manager's name.
# This ensures that all order details remain, and manager information is added where a matching region exists.
final_dataset = final_dataset.merge(people, on='Region', how='left')

print("Shape of the final dataset:", final_dataset.shape)
print("\nFirst 5 rows of the final dataset:")
display(final_dataset.head())

print("\nInformation about the final dataset:")
final_dataset.info()

Shape of the final dataset: (5000, 23)

First 5 rows of the final dataset:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Returned,Person
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,No,Cassandra Brandow
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,No,Cassandra Brandow
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,No,Anna Andreadi
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,No,Cassandra Brandow
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,No,Cassandra Brandow

Information about the final dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5000 non-null   int64
 1   Order ID       5000 non-null   object
 2   Order Date     5000 non-null   datetime64[ns]
 3   Ship Date      5000 non-null   datetime64[ns]
 4   Ship Mode      5000 non-null   object
 5   Customer ID    5000 non-null   object
 6   Customer Name  5000 non-null   object
 7   Segment        5000 non-null   object
 8   Country        5000 non-null   object
 9   City           5000 non-null   object
 10  State          5000 non-null   object
 11  Postal Code    5000 non-null   int64
 12  Region         5000 non-null   object
 13  Product ID     5000 non-null   object
 14  Category       5000 non-null   object
 15  Sub-Category   5000 non-null   object
 16  Product Name   5000 non-null   object
 17  Sales          5000 non-null   float64
 18  Quantity       5000 non-null   int64
 19  Discount       5000 non-null   float64
 20  Profit         5000 non-null   float64
 21  Returned       5000 non-null   object
 22  Person         5000 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(3), object(15)
memory usage: 898.6+ KB

### 360-Degree Data View

In [37]:
# Display general information about the DataFrame, including data types and non-null counts
print("\nGeneral Information of the final dataset:")
final_dataset.info()

General Information of the final dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5000 non-null   int64
 1   Order ID       5000 non-null   object
 2   Order Date     5000 non-null   datetime64[ns]
 3   Ship Date      5000 non-null   datetime64[ns]
 4   Ship Mode      5000 non-null   object
 5   Customer ID    5000 non-null   object
 6   Customer Name  5000 non-null   object
 7   Segment        5000 non-null   object
 8   Country        5000 non-null   object
 9   City           5000 non-null   object
 10  State          5000 non-null   object
 11  Postal Code    5000 non-null   int64
 12  Region         5000 non-null   object
 13  Product ID     5000 non-null   object
 14  Category       5000 non-null   object
 15  Sub-Category   5000 non-null   object
 16  Product Name   5000 non-null   object
 17  Sales          5000 non-null   float64
 18  Quantity       5000 non-null   int64
 19  Discount       5000 non-null   float64
 20  Profit         5000 non-null   float64
 21  Returned       5000 non-null   object
 22  Person         5000 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(3), object(15)
memory usage: 898.6+ KB

#### Summary Statistics for Numerical Columns

In [38]:
# Display summary statistics for numerical columns
print("\nSummary Statistics for Numerical Columns:")
display(final_dataset[['Sales', 'Quantity', 'Discount', 'Profit']].describe())

Summary Statistics for Numerical Columns:

              Sales     Quantity     Discount       Profit
count   5000.000000  5000.000000  5000.000000  5000.000000
mean     228.079745     3.794800     0.156966    25.674527
std      630.311081     2.240022     0.206837   208.757765
min        0.444000     1.000000     0.000000 -3839.990400
25%       16.560000     2.000000     0.000000     1.760800
50%       52.236000     3.000000     0.200000     8.627500
75%      211.027000     5.000000     0.200000    28.786800
max    22638.480000    14.000000     0.800000  5039.985600

#### Summary Statistics for Categorical Columns

In [39]:
# Display summary statistics for categorical columns

print("\nSummary Statistics for Categorical Columns (Region, Segment, Category, Sub-Category):")
for col in ['Region', 'Segment', 'Category', 'Sub-Category']:
    print(f"\n--- {col} ---")
    display(final_dataset[col].value_counts())
    print(f"Number of unique {col}: {final_dataset[col].nunique()}")

Summary Statistics for Categorical Columns (Region, Segment, Category, Sub-Category):

--- Region ---

Region
West       1607
East       1435
Central    1156
South       802
Name: count, dtype: int64

Number of unique Region: 4

--- Segment ---

Segment
Consumer       2657
Corporate      1422
Home Office     921
Name: count, dtype: int64

Number of unique Segment: 3

--- Category ---

Category
Office Supplies    3057
Furniture          1035
Technology          908
Name: count, dtype: int64

Number of unique Category: 3

--- Sub-Category ---

Sub-Category
Binders        779
Paper          681
Furnishings    464
Phones         449
Storage        432
Art            419
Accessories    369
Chairs         302
Appliances     221
Labels         179
Tables         159
Envelopes      134
Fasteners      124
Bookcases      110
Supplies        88
Machines        58
Copiers         32
Name: count, dtype: int64

Number of unique Sub-Category: 17

#### Checking for Duplicate Rows

In [40]:
# Check for duplicate rows
duplicate_rows = final_dataset.duplicated().sum()
print(f"\nNumber of duplicate rows: {duplicate_rows}")
if duplicate_rows > 0:
    print("\nDisplaying first 5 duplicate rows:")
    display(final_dataset[final_dataset.duplicated()].head())

Number of duplicate rows: 0

#### Checking for Missing Values

In [41]:
# Check for missing values in each column
print("\nMissing values per column:")
display(final_dataset.isnull().sum())

Missing values per column:

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Returned         0
Person           0
dtype: int64

### Managerial Request: Records from San Francisco with Sales Exceeding 1,000

In [42]:
# Filter records where City is 'San Francisco' and Sales exceed 1,000
san_francisco_high_sales = final_dataset[(final_dataset['City'] == 'San Francisco') & (final_dataset['Sales'] > 1000)]

print(f"Number of records from San Francisco with sales exceeding 1,000: {len(san_francisco_high_sales)}")
print("\nQuick summary of these records (first 5 rows):")
display(san_francisco_high_sales.head())

Number of records from San Francisco with sales exceeding 1,000: 20

Quick summary of these records (first 5 rows):

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Returned,Person
406,407,CA-2017-117457,2017-12-08,2017-12-12,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Francisco,...,TEC-CO-10004115,Technology,Copiers,Sharp AL-1530CS Digital Copier,1199.976,3,0.20,434.9913,No,Anna Andreadi
408,409,CA-2017-117457,2017-12-08,2017-12-12,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Francisco,...,FUR-TA-10002041,Furniture,Tables,"Bevis Round Conference Table Top, X-Base",1004.024,7,0.20,-112.9527,No,Anna Andreadi
412,413,CA-2017-117457,2017-12-08,2017-12-12,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Francisco,...,FUR-BO-10001972,Furniture,Bookcases,O'Sullivan 4-Shelf Bookcase in Odessa Pine,1336.829,13,0.15,31.4548,No,Anna Andreadi
551,552,CA-2016-136406,2016-04-15,2016-04-17,Second Class,BD-11320,Bill Donatelli,Consumer,United States,San Francisco,...,FUR-CH-10002024,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,1121.568,2,0.20,0.0000,No,Anna Andreadi
753,754,CA-2016-110499,2016-04-07,2016-04-09,First Class,YC-21895,Yoseph Carroll,Corporate,United States,San Francisco,...,TEC-CO-10002095,Technology,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,1199.976,3,0.20,374.9925,No,Anna Andreadi

In [44]:
num_records = len(san_francisco_high_sales)
total_sales_value = san_francisco_high_sales['Sales'].sum()

print(f"Number of matching records: {num_records}")
print(f"Total Sales value for these records: ${total_sales_value:,.2f}")

Number of matching records: 20
Total Sales value for these records: $37,443.53

### Insights from San Francisco High Sales Records

In [45]:
# Analyze top categories and sub-categories for high sales in San Francisco
print("\nTop Categories in San Francisco High Sales:")
display(san_francisco_high_sales['Category'].value_counts())

print("\nTop Sub-Categories in San Francisco High Sales:")
display(san_francisco_high_sales['Sub-Category'].value_counts().head(5))

# Analyze profitability of these high sales
mean_profit = san_francisco_high_sales['Profit'].mean()
total_profit = san_francisco_high_sales['Profit'].sum()
print(f"\nAverage Profit per high-sales transaction in San Francisco: ${mean_profit:,.2f}")
print(f"Total Profit from high-sales transactions in San Francisco: ${total_profit:,.2f}")

# Analyze average sales and discounts
mean_sales = san_francisco_high_sales['Sales'].mean()
mean_discount = san_francisco_high_sales['Discount'].mean()
print(f"Average Sales amount per high-sales transaction in San Francisco: ${mean_sales:,.2f}")
print(f"Average Discount applied to high-sales transactions in San Francisco: {mean_discount:.2%}")

Top Categories in San Francisco High Sales:

Category
Furniture          9
Technology         7
Office Supplies    4
Name: count, dtype: int64

Top Sub-Categories in San Francisco High Sales:

Sub-Category
Copiers      3
Tables       3
Bookcases    3
Chairs       3
Phones       2
Name: count, dtype: int64

Average Profit per high-sales transaction in San Francisco: $159.10
Total Profit from high-sales transactions in San Francisco: $3,182.05
Average Sales amount per high-sales transaction in San Francisco: $1,872.18
Average Discount applied to high-sales transactions in San Francisco: 15.25%